/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as SearchImport } from './routes/search'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as NotificationsIndexImport } from './routes/notifications/index'
import { Route as FavouritesIndexImport } from './routes/favourites/index'
import { Route as TagsTagIdImport } from './routes/tags/$tagId'
import { Route as ExperiencesNewImport } from './routes/experiences/new'
import { Route as UsersUserIdIndexImport } from './routes/users/$userId/index'
import { Route as ExperiencesExperienceIdIndexImport } from './routes/experiences/$experienceId/index'
import { Route as UsersUserIdFollowingImport } from './routes/users/$userId/following'
import { Route as UsersUserIdFollowerImport } from './routes/users/$userId/follower'
import { Route as ExperiencesExperienceIdEditImport } from './routes/experiences/$experienceId/edit'
import { Route as ExperiencesExperienceIdAttendeesImport } from './routes/experiences/$experienceId/Attendees'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NotificationsIndexRoute = NotificationsIndexImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRoute,
} as any)

const FavouritesIndexRoute = FavouritesIndexImport.update({
  id: '/favourites/',
  path: '/favourites/',
  getParentRoute: () => rootRoute,
} as any)

const TagsTagIdRoute = TagsTagIdImport.update({
  id: '/tags/$tagId',
  path: '/tags/$tagId',
  getParentRoute: () => rootRoute,
} as any)

const ExperiencesNewRoute = ExperiencesNewImport.update({
  id: '/experiences/new',
  path: '/experiences/new',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserIdIndexRoute = UsersUserIdIndexImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => rootRoute,
} as any)

const ExperiencesExperienceIdIndexRoute =
  ExperiencesExperienceIdIndexImport.update({
    id: '/experiences/$experienceId/',
    path: '/experiences/$experienceId/',
    getParentRoute: () => rootRoute,
  } as any)

const UsersUserIdFollowingRoute = UsersUserIdFollowingImport.update({
  id: '/users/$userId/following',
  path: '/users/$userId/following',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserIdFollowerRoute = UsersUserIdFollowerImport.update({
  id: '/users/$userId/follower',
  path: '/users/$userId/follower',
  getParentRoute: () => rootRoute,
} as any)

const ExperiencesExperienceIdEditRoute =
  ExperiencesExperienceIdEditImport.update({
    id: '/experiences/$experienceId/edit',
    path: '/experiences/$experienceId/edit',
    getParentRoute: () => rootRoute,
  } as any)

const ExperiencesExperienceIdAttendeesRoute =
  ExperiencesExperienceIdAttendeesImport.update({
    id: '/experiences/$experienceId/Attendees',
    path: '/experiences/$experienceId/Attendees',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/experiences/new': {
      id: '/experiences/new'
      path: '/experiences/new'
      fullPath: '/experiences/new'
      preLoaderRoute: typeof ExperiencesNewImport
      parentRoute: typeof rootRoute
    }
    '/tags/$tagId': {
      id: '/tags/$tagId'
      path: '/tags/$tagId'
      fullPath: '/tags/$tagId'
      preLoaderRoute: typeof TagsTagIdImport
      parentRoute: typeof rootRoute
    }
    '/favourites/': {
      id: '/favourites/'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesIndexImport
      parentRoute: typeof rootRoute
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/experiences/$experienceId/Attendees': {
      id: '/experiences/$experienceId/Attendees'
      path: '/experiences/$experienceId/Attendees'
      fullPath: '/experiences/$experienceId/Attendees'
      preLoaderRoute: typeof ExperiencesExperienceIdAttendeesImport
      parentRoute: typeof rootRoute
    }
    '/experiences/$experienceId/edit': {
      id: '/experiences/$experienceId/edit'
      path: '/experiences/$experienceId/edit'
      fullPath: '/experiences/$experienceId/edit'
      preLoaderRoute: typeof ExperiencesExperienceIdEditImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId/follower': {
      id: '/users/$userId/follower'
      path: '/users/$userId/follower'
      fullPath: '/users/$userId/follower'
      preLoaderRoute: typeof UsersUserIdFollowerImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId/following': {
      id: '/users/$userId/following'
      path: '/users/$userId/following'
      fullPath: '/users/$userId/following'
      preLoaderRoute: typeof UsersUserIdFollowingImport
      parentRoute: typeof rootRoute
    }
    '/experiences/$experienceId/': {
      id: '/experiences/$experienceId/'
      path: '/experiences/$experienceId'
      fullPath: '/experiences/$experienceId'
      preLoaderRoute: typeof ExperiencesExperienceIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/experiences/new': typeof ExperiencesNewRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/favourites': typeof FavouritesIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/experiences/$experienceId/Attendees': typeof ExperiencesExperienceIdAttendeesRoute
  '/experiences/$experienceId/edit': typeof ExperiencesExperienceIdEditRoute
  '/users/$userId/follower': typeof UsersUserIdFollowerRoute
  '/users/$userId/following': typeof UsersUserIdFollowingRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/experiences/new': typeof ExperiencesNewRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/favourites': typeof FavouritesIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/experiences/$experienceId/Attendees': typeof ExperiencesExperienceIdAttendeesRoute
  '/experiences/$experienceId/edit': typeof ExperiencesExperienceIdEditRoute
  '/users/$userId/follower': typeof UsersUserIdFollowerRoute
  '/users/$userId/following': typeof UsersUserIdFollowingRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/experiences/new': typeof ExperiencesNewRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/favourites/': typeof FavouritesIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/experiences/$experienceId/Attendees': typeof ExperiencesExperienceIdAttendeesRoute
  '/experiences/$experienceId/edit': typeof ExperiencesExperienceIdEditRoute
  '/users/$userId/follower': typeof UsersUserIdFollowerRoute
  '/users/$userId/following': typeof UsersUserIdFollowingRoute
  '/experiences/$experienceId/': typeof ExperiencesExperienceIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/search'
    | '/settings'
    | '/experiences/new'
    | '/tags/$tagId'
    | '/favourites'
    | '/notifications'
    | '/experiences/$experienceId/Attendees'
    | '/experiences/$experienceId/edit'
    | '/users/$userId/follower'
    | '/users/$userId/following'
    | '/experiences/$experienceId'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/search'
    | '/settings'
    | '/experiences/new'
    | '/tags/$tagId'
    | '/favourites'
    | '/notifications'
    | '/experiences/$experienceId/Attendees'
    | '/experiences/$experienceId/edit'
    | '/users/$userId/follower'
    | '/users/$userId/following'
    | '/experiences/$experienceId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/search'
    | '/settings'
    | '/experiences/new'
    | '/tags/$tagId'
    | '/favourites/'
    | '/notifications/'
    | '/experiences/$experienceId/Attendees'
    | '/experiences/$experienceId/edit'
    | '/users/$userId/follower'
    | '/users/$userId/following'
    | '/experiences/$experienceId/'
    | '/users/$userId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ExperiencesNewRoute: typeof ExperiencesNewRoute
  TagsTagIdRoute: typeof TagsTagIdRoute
  FavouritesIndexRoute: typeof FavouritesIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  ExperiencesExperienceIdAttendeesRoute: typeof ExperiencesExperienceIdAttendeesRoute
  ExperiencesExperienceIdEditRoute: typeof ExperiencesExperienceIdEditRoute
  UsersUserIdFollowerRoute: typeof UsersUserIdFollowerRoute
  UsersUserIdFollowingRoute: typeof UsersUserIdFollowingRoute
  ExperiencesExperienceIdIndexRoute: typeof ExperiencesExperienceIdIndexRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ExperiencesNewRoute: ExperiencesNewRoute,
  TagsTagIdRoute: TagsTagIdRoute,
  FavouritesIndexRoute: FavouritesIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  ExperiencesExperienceIdAttendeesRoute: ExperiencesExperienceIdAttendeesRoute,
  ExperiencesExperienceIdEditRoute: ExperiencesExperienceIdEditRoute,
  UsersUserIdFollowerRoute: UsersUserIdFollowerRoute,
  UsersUserIdFollowingRoute: UsersUserIdFollowingRoute,
  ExperiencesExperienceIdIndexRoute: ExperiencesExperienceIdIndexRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/register",
        "/search",
        "/settings",
        "/experiences/new",
        "/tags/$tagId",
        "/favourites/",
        "/notifications/",
        "/experiences/$experienceId/Attendees",
        "/experiences/$experienceId/edit",
        "/users/$userId/follower",
        "/users/$userId/following",
        "/experiences/$experienceId/",
        "/users/$userId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/experiences/new": {
      "filePath": "experiences/new.tsx"
    },
    "/tags/$tagId": {
      "filePath": "tags/$tagId.tsx"
    },
    "/favourites/": {
      "filePath": "favourites/index.tsx"
    },
    "/notifications/": {
      "filePath": "notifications/index.tsx"
    },
    "/experiences/$experienceId/Attendees": {
      "filePath": "experiences/$experienceId/Attendees.tsx"
    },
    "/experiences/$experienceId/edit": {
      "filePath": "experiences/$experienceId/edit.tsx"
    },
    "/users/$userId/follower": {
      "filePath": "users/$userId/follower.tsx"
    },
    "/users/$userId/following": {
      "filePath": "users/$userId/following.tsx"
    },
    "/experiences/$experienceId/": {
      "filePath": "experiences/$experienceId/index.tsx"
    },
    "/users/$userId/": {
      "filePath": "users/$userId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
